spring:
  profiles:
    active: consumer1
---
spring:
  profiles: publish
  rabbitmq:
    addresses: 192.168.186.149
    username: admin
    password: admin
    publisher-returns: true
    publisher-confirms: true
server:
  port: 8080

---
spring:
  profiles: consumer1
  rabbitmq:
    addresses: 192.168.186.149
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
server:
  port: 8081

---
spring:
  profiles: consumer2
  rabbitmq:
    addresses: 192.168.186.149
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
server:
  port: 8082

