server:
  port: 9001
spring:
  application:
    name: feignDemo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500