spring:
  profiles:
    active: publish
---
spring:
  profiles: publish
  rabbitmq:
    addresses: 192.168.186.149
    username: admin
    password: admin
server:
  port: 8080

---
spring:
  profiles: consumer1
  rabbitmq:
    addresses: 192.168.186.149
    username: admin
    password: admin
server:
  port: 8081

---
spring:
  profiles: consumer2
  rabbitmq:
    addresses: 192.168.186.149
    username: admin
    password: admin
server:
  port: 8082