spring:
  application:
    name: eurekapeer1

server:
  port: 10001

eureka:
  instance:
    hostname: prodEurekaServer
    instance-id: prodEurekaServer
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10000/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10001

