spring:
  application:
    name: eurekaDemo

server:
  port: 10002

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10001/eureka,http://localhost:10002/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"