server:
  port: 7001
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/szwkang/cloudconfig #配置文件所在仓库
          search-paths: /config
          default-label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
